### PR TITLE
Basic support for Swift PM

### PR DESCRIPTION
**Pull request by UberJason**
Here's a quick stab at support for Swift PM (#171). I'm still fairly new to Swift PM myself, but this does seem to work. 

In the process I noticed that one file, Date+Manipulations.swift, seemed to be in the wrong folder - it was in Tests but looks like it's supposed to be part of the core library, and builds were failing because they were expecting that file. So I moved that file.

I don't know how much or little you care about this, but this PR of mine is not exactly the way it's "supposed" to be done. My PR makes as minimal changes to the existing code as possible to support SwiftPM, in part by excluding the Examples and Tests. Swift PM prefers source files (and only Swift files) to be in a folder called `Sources/`, and for all Test folders to end in "Tests". I've got a branch called `swift-pm-the-right-way` in my fork of DateTools which makes more involved changes that you can look at to see if you care about this or not.

Finally, by the way, note that SwiftPM works by git tag (just like GitHub releases), so even after you accept this PR, I don't think it'll work with Swift PM until you've created and tagged another formal release that includes this commit.

### CODE REVIEW

**Comment by MatthewYork** [comment]
You are right on Date+Manipulations. It was added late and we forgot to place it in the proper directory. I am going to try to resolve the conflicts while maintaining your contribution here.

Really appreciate this!

**Comment by MatthewYork** [comment]
Looks like it merged cleanly! We will do our best to get a swift package up whenever we are ready to hit gold master. Also, just a quick question: does the Capital One app use DateTools? If so, we would gladly advertise it on the main page for you guys!

**Comment by UberJason** [comment]
Awesome, I'll probably have another PR coming soon with some fixes for Linux compatibility too. I don't work on the main Capital One app - I'm part of the Capital One Labs organization, we do a lot of rapid prototyping on new app experiences, and my current project is considering using DateTools. (I've used DateTools on several projects in the past, though.) So I wouldn't know if the main app uses it or not. 

(Incidentally, how did you know I'm with Capital One? Not that it's a secret, but I didn't know it was obvious from my personal GitHub here. :) )

**Comment by MatthewYork** [comment]
Thanks for that. I am actually doing some light linux work too, and would love to get DateTools up and running.

As for Capital One, the email showed up in one of the commits you made. Must have been the git account email from a machine you committed from! Since we are always looking for new contributors to list, I wanted to ask. And thanks for using DateTools in the past! Hopefully this new version will be enough to sustain and grow the library.

**Pull request merged**
