### PR TITLE
Carthage compatible

### PR DESCRIPTION
**Pull request by morizotter**
[Carthage](https://github.com/Carthage/Carthage) is very powerful dependency manager.

It is very easy to be compatible with Carthage. - [Supporting carthage for your framework](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)

I made DateTools compatible with Carthage in this pull request. I used existing Example project because I don't want to pollute your directory structure. But different directory structure mabye better.

I like this better than Cocoapods because when clean and build project, cocoapods rebuild libraries again, but Carthage doesn't do that. Swift's build time is very long. So, it is helpfull to install library with Carthage.

Thanks!

### CODE REVIEW

**Comment by MatthewYork** [comment]
I REALLY want to add this, but working out the conflicts might be difficult for me as I do not use Carthage. Is there any way you could resolve these conflicts so I can merge your additions in? 

Thanks,

-Matt

**Comment by morizotter** [comment]
Hi, thanks:)

But I think you maybe wait for merging this pull request. Because unstable release is not good for you :)

You better take this pull request just as a suggestion.

Any way, I fix the conflict. I like Carthage so, I fork it if it is not compatible with carthage. But it's better library itself is compatible with Carthage:)

I write how to make this project compatible with Carthage.

---

## 1. Create framework target



## 2. Make scheme sharable



## 3. Add source files and make header public

You can change header as public in File inspector.



## 4. Edit DateTools.h

Framework target generate default DateTools.h. It's name is same to DateTools.h. So, I merged these to file's content.

## 5. Check if it works

Use Carthage in sample project.

```
let timeAgoDate = NSDate(timeIntervalSinceNow: -4)
println("\(timeAgoDate.timeAgoSinceNow())")
println("\(timeAgoDate.shortTimeAgoSinceNow())")
```

**Comment by morizotter** [comment]
And I think the carthage framework location is not the best place in Example.project. I did there because I hesitated to change your directory structure.

I searched a little about Carthage compatible library written in Objective-C. For example, https://github.com/Mantle/Mantle . It locate framework at the top level. I think it is better. I always put my carthage framework in top level too.

**Comment by daniel-shin1104** [comment]
+1

**Comment by MatthewYork** [comment]
Merged!

**Comment by MatthewYork** [comment]
Please check to make sure everything is working for you! Thanks,

-Matt

**Comment by lukescott** [comment]
Last time I checked the latest version of Carthage no longer looks for xcodeproj files in subdirectories. If that is still the case this won't work.

**Pull request merged**
