### PR TITLE
Add Carthage support for iOS 8.0 and OS X 10.7

### PR DESCRIPTION
**Pull request by lukescott**
Adds Carthage support for iOS 8.0 and OS X 10.7 as separate targets. README updated and tests moved to root project.

The build target PR #101 is iOS 9.0.

### CODE REVIEW

**Comment by MatthewYork** [comment]
We <i>should</i> have fixed this today by merging someone else's commit from earlier. Please check that the current master branch is Carthage compatible. I do not use it, so I can only go by what people who use it tell me.

Thanks,

-Matt

**Comment by lukescott** [comment]
I'll check when I have a chance, but as far as I know it won't work. Carthage (latest version) only checks for xcodeproj files in the root directory now. I'll have to verify that is still the case.

**Comment by MatthewYork** [comment]
Interesting... Please let me know what you find with this. If you are sure it doesn't work (or that there is no way to indicate build subdirectories), I will remove my claim of support for Carthage.

**Comment by MatthewYork** [comment]
Can we just add a top level build file (I am on mobile, so I am not sure if that is what you have done) that references already existing files?

**Comment by lukescott** [comment]
Hmm. It does seem to work, which is odd because I've had two other projects not work because of xcodeproj location not being in root. However, the current target is set to iOS 8.4 (should be 8.0) and the OS X target is missing.

Yes, this PR makes a top level build file and references the existing files. Although the tests were moved into the root project. I also fixed one test that was failing due to the language file not being located. The targets are also iOS 8.0 and OS X 10.7.

Carthage is simple to use:

```
brew install carthage
mkdir ~/Desktop/test
echo 'github "MatthewYork/DateTools"' >> Cartfile
carthage update
```

From there you add `./Carthage/Build/iOS/DateTools.framework` to your project as an embedded framework. Carthage uses xcode to build, and it doesn't mess with your project file. It's the closest thing to using pure xcode as you can get.

**Comment by MatthewYork** [comment]
So, in your opinion, would it make more sense to just adjust the build target in the current project and ass an OS X target? If so, I would be glad to let you do those things for the contribution and because it seems more your expertise.

**Comment by lukescott** [comment]
This is what @morizotter said as the last comment in his PR:
> And I think the carthage framework location is not the best place in Example.project. I did there because I hesitated to change your directory structure.

I would agree with him there. It took some work to setup the OS X target. Since the work is already there, I'd rather merge this PR. Or just reduce the target in the example project from 8.4 to 8.0. I just need this for an iOS project, so either of those options work for me.

**Comment by enricenrich** [comment]
Any updates on this? :)

**Comment by rcdilorenzo** [comment]
I'd also like to get this merged. Any update?

P.S. @MatthewYork, I was blessed to see a reference to Acts in your README.

**Pull request closed without merging**
