### PR TITLE
Support Carthage & the swift package manager

### PR DESCRIPTION
**Pull request by AndrewSB**
Hey Matthew!

I saw https://github.com/MatthewYork/DateTools/issues/27#issuecomment-256435305, where you said you were looking to support Carthage and spm. I went ahead and created a PR that does the two 😄 

I also just integrated DateTools (using Carthage) into my app and it's working great! Thank you for your work

Let me know if there are any changes I should make before you're comfortable merging this in!

### CODE REVIEW

**Comment by AndrewSB** [comment]
@graysonwebster @MatthewYork no rush on this at all! I know updating to swift3 is a major task 🙃

I was wondering if you guys were planning to use the changes in this PR, if so I can rebase the new changes in so they're ready for you when you're ready for them. If not then I'll probably ditch this request so I can keep up with the changes the two of you have been making on `swift3`

Thank you for all of your work, the both of you 😄

**Comment by MatthewYork** [comment]
Andrew, we are definitely hoping to pull in support for Carthage, SPM. Are these file location changes that are causing the conflicts? What, generally speaking, are you doing to bring in this new functionality. 

I am hesitant to merge with all the file conflicts, but definitely hope to get this sorted out!

**Comment by AndrewSB** [comment]
They are mostly file location changes that happened when @graysonwebster added a different Xcode project. Let me try branching off `swift` now, and re-doing my changes. I can explain them in the next pull request I create

**Comment by AndrewSB** [comment]
Created #184

**Pull request closed without merging**
