### PR TITLE
Enabling app extension API only

### PR DESCRIPTION
**Pull request by JamieWhite**
This setting needs to be enabled to silence warnings when using this Framework in an app extension.

Details are on this apple doc: https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html under "Using an Embedded Framework to Share Code"

Toggling this on basically stops us from using any APIs that are not allowed in app extensions such as UIApplication.sharedApplication() - which we're not.

### CODE REVIEW

**Comment by JamieWhite** [comment]
Any thoughts on this one?

**Comment by JamieWhite** [comment]
Is this framework even maintained anymore?

**Comment by MatthewYork** [comment]
It is. I am awaiting a rewrite opportunity with Swift 3.0, but will continue maintenance at least until then.

If you look back, all of the pull requests have been in chunks every few months. I get to them when I can. Sorry for the inconvenience! I will try to get this update reviewed and merged soon.

**Comment by JamieWhite** [comment]
I appreciate you've probably got more things to do than devote 100% of your time to this but I'm curious; why are you waiting until Swift 3.0? If you're following the Swift evolution docs you'll know that not a lot of changing for it and you could even start coding for it now. By the time Swift 3.0 is out and you find time to do a rewrite other frameworks will fill the gap and make DateTools irrelevant.

**Comment by MatthewYork** [comment]
Definitely a valid concern. I may begin the rewrite early.. I have just been screwed over a few times with paradigm changes from swift 0.x, 1.x and 2.x

I will get these changes looked at soon and begin a dedicated discussion for the swift version. I already have a few ideas, but would love to see what everyone else comes up with for the next iteration. Getting married in March, so things are a bit crazy at the moment.

**Comment by JamieWhite** [comment]
8 months now to merge in this 2 line change. I appreciate you're busy but this is two lines.

**Comment by JamieWhite** [comment]
@MatthewYork I see you've been active again. Mind merging in this change?

**Comment by JamieWhite** [comment]
I see you now have a macOS target so I've added the same toggle for that too.

**Comment by aaronbrethorst** [comment]
I'd love to see this merged.

**Comment by MatthewYork** [comment]
Thank you for your patience!

**Pull request merged**
