### PR TITLE
[DT-56]: Updates the macro to safely locate the localization bundle.

### PR DESCRIPTION
**Pull request by danthorpe**
Fixes issues #56, and #69

### CODE REVIEW

**Comment by jlalvarez18** [comment]
Merge this badboy! We need it ASAP!

**Comment by jlalvarez18** [comment]
@MatthewYork please fix approve this merge.. this is a huge issue in cocoa pods

**Comment by MatthewYork** [comment]
I will reissue a new cocoa pod very soon.

My apologies for taking so long! I have had a lot going on.

**Comment by jlalvarez18** [comment]
@MatthewYork I absolutely understand and I thank you for the quick response. You are a gentleman and a scholar :)

**Comment by MatthewYork** [comment]
Haha. Thank you!

I am seeing a crash running the unit tests after this merge, but it could be from a previous merge. Once I get that bug tracked down, we should be good to go. I will post back here when everything is done.

**Comment by MatthewYork** [comment]
It appears that this change:

```objc
#ifndef DateToolsLocalizedStrings
 #define DateToolsLocalizedStrings(key) \
-NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil)
+NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle bundleForClass:[DTError class]] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil)
 #endif
```

is what is causing the crash when running unit tests. When I remove the error bundling and return it to the mainBundle, everything works find. @danthorpe or @jlalvarez18 , is their any harm in doing this? Just wondering what the initial change is all about. At this point, I am a bit removed from the code, so an explanation would be great.

Thanks,

-Matt

**Comment by danthorpe** [comment]
@MatthewYork Hmm, as I recall, the fix is to make it so that the bundle is loaded from whichever bundle also contains `DTError.h`. This is so that when DateTools is packaged as a framework (e.g. using `use_frameworks` with CocoaPods), everything works. 

The unit tests project add the files under test to both the app - DateToolsTests, but also the test target  DateToolsTestsTests - and this makes the macro fail I guess.

I've submitted a new pull request: https://github.com/MatthewYork/DateTools/pull/84

**Comment by davetroy** [comment]
This seems to be broken under CocoaPods 1.0; have not identified a workaround yet.

**Pull request merged**
