### PR TITLE
Carthage & Swift package manager support

### PR DESCRIPTION
**Pull request by AndrewSB**
Continues #182. The gist of this change is creating just one xcodeproj in the root directory, that exposes the source, and all the examples and tests

The xcodeproj shares the DateTools scheme so carthage can pick it up (I'm using my branch through Carthage on production)

### CODE REVIEW

**Comment by AndrewSB** [comment]
@MatthewYork this is ready to go, let me know if you have any questions or would like any changes!

**Comment by mark-anders** [comment]
It would be great to see this integrated.  One question - does it work for the swift branch, since that seems to be a completely different codebase?  I just switched to it after having used the Objective-C version and it doesn't build.  I the following error:

     Dependency "DateTools" has no shared framework schemes for any of the platforms: iOS

**Comment by AndrewSB** [comment]
@mark-anders you're using Carthage, I presume? 
You'll have to tell it to point to my fork (`github "AndrewSB/DateTools" "swift3"`) until the changes are merged in to @MatthewYork's repo.

I'm using my fork in a prod app right now, so I'm committed to keeping my branch up to date until DateTools merges this in/ supports Carthage in another way

**Comment by mark-anders** [comment]
@AndrewSB - thanks for the tip!  I actually did a fork and created an xcode project too.  Unfortunatley I then discovered that this is swift 3 only and I'm still on 2.3. :-(

Thank you though!

**Comment by AndrewSB** [comment]
Ahh, I totally understand. Is DateTools planning to support swift 2.3? If so, we can combine our pull requests and just have one that supports carthage on both 2.3 and 3?

**Comment by mark-anders** [comment]
@AndrewSB  - I would doubt it.  if they were going to support it the way to do it would have been to do 2.3 and then migrate that to 3.0.  I think it's probably hard to go the other way.  Just be clear - I don't have a pull request for a 2.3 branch.  Just an xcode project that doesn't build when you set legacy swift version to true.

**Comment by AndrewSB** [comment]
Oh, I see. I thought you meant you had a fork building in swift 2.3, and
the only thing I had to do to support was switch `USE_LEGACY_SWIFT` on 😅

**Comment by AndrewSB** [comment]
@MatthewYork I'd love to get this merged in sooner rather than later. Adding many more commits to the `swift` branch will no doubt create merge conflicts that we'll have to deal with later

**Comment by AndrewSB** [comment]
let me know if I should resolve conflicts so you can merge :)

**Comment by MatthewYork** [comment]
So, there was a separate PR has potentially fixed swift package management. Can you verify that the additions for Carthage work in the new repository structure with DateTools and DateToolsSwift folders?

Thanks,

-Matt

**Comment by AndrewSB** [comment]
@MatthewYork: It does fix the SPM setup, but not Carthage. I still think this PR should be merged in. 

It also renames the "DateToolSwift" target to "DateTool", unbreaking the problem that #201 solved as well :)

**Comment by AndrewSB** [comment]
@MatthewYork: whats the status on this? I'd love to get this merged in so I can delete my fork

**Comment by 3a4oT** [comment]
@MatthewYork ping

**Comment by JanC** [comment]
Hi,
any update on this?

**Comment by YauheniYarotski** [comment]
Yep, cartage is really good to have, please.

**Comment by JakubMazur** [comment]
That's a good PR, please merge it to master branch

**Comment by 3a4oT** [comment]
Hey, all I have created a hard fork of *DateTools* and made it **Carthage compatible** for my own needs. Hope [DateToolsObjC](https://github.com/3a4oT/DateToolsObjC) will help someone else. Of course, all copyrights were saved.

**Comment by caiodias** [comment]
@MatthewYork can you please accept this PR?

**Comment by valeriyvan** [comment]
Any chance this will be merged?

**Comment by lukescott** [comment]
It looks like this PR is targeting the swift branch. When I try to merge this with the master branch (which is more up to date) I get a ton of merge conflicts.

**Comment by AndrewSB** [comment]
https://github.com/MatthewYork/DateTools/pull/184#issuecomment-269562557 it's like I predicted the future 🧐

**Comment by lukescott** [comment]
Currently being blocked by this. Xcode is wanting Swift 4 and this is the only dependency that isn't working.

**Comment by AndrewSB** [comment]
Check out the xcodebuild.log, I'm not using this library anymore so it's probably some code that's incompatible with Swift 4.

I don't know if its better to continue to use the swift branch, or fix master because its 45 commits further ahead, so 🤷‍♂️

**Comment by lukescott** [comment]
I ended up switching to SwiftDate.

**Comment by AndrewSB** [comment]
closing this because I imagine it will never be merged and I'd like to delete my fork

**Pull request closed without merging**
