### PR TITLE
Adding xcode project to build iOS framework with Carthage

### PR DESCRIPTION
**Pull request by Visorox**
Added this so that DateTools can be compatible with Carthage

### CODE REVIEW

**Comment by Visorox** [comment]
Hah, I've just realised there's a pull request open for this. I started this a few weeks back before the other PR but I've been on holiday since so didn't have time to PR it.

Feel free to close this if you prefer the other one.

**Comment by lukescott** [comment]
This one seems cleaner than the other one. Please merge. Will use fork until then, thanks @Visorox!

**Comment by lukescott** [comment]
The target is set to iOS 9. Also the travis build seems to have failed - none of the tests actually ran.

**Comment by Visorox** [comment]
Looks like it's running fine to me.

**Comment by lukescott** [comment]
@Visorox see https://travis-ci.org/MatthewYork/DateTools/builds/74932580

**Pull request closed without merging**
