### PR TITLE
Swiftpm support

### PR DESCRIPTION
**Pull request by maniramezan**
Fix the issue with SwiftPM setup and add auto generated files to `.gitignore`

### CODE REVIEW

**Comment by bryan1anderson** [comment]
@maniramezan This fails at `return Bundle(path: NSString(string: assetPath).appendingPathComponent("DateTools.bundle"))!`
Force unwrap a nil optional. Are bundles allowed in SwiftPM at the moment? I didn't think resource files were allowed

**Comment by maniramezan** [comment]
@bryan1anderson Yeah, so far it's not possible to add bundles to SwiftPM, [package manager resources](https://github.com/abertelrud/swift-evolution/blob/package-manager-resources/proposals/NNNN-package-manager-resources.md) seems to be a proposal for it. For now, it requires to add them manually.

**Comment by MatthewYork** [comment]
Alright, I have returned. Quit my job, started a business, and had a child....

But definitely ready to merge in SwiftPM support! Please see the recent Swift 5 release and re-evaluate the pull request just to make sure none of my changes bothered yours.

Really appreciate it!

**Comment by MatthewYork** [comment]
I'm going to close this request. Please reopen branching off the new release and I will merge. Thanks!

**Comment by maniramezan** [comment]
@MatthewYork Congrats! 🍾🎉

I opened a PR regarding adding SwiftPM https://github.com/MatthewYork/DateTools/pull/291 based on latest `master`.

**Pull request closed without merging**
