### PR TITLE
NSbundle fix

### LINKED ISSUE #56: Crash when using with cocoapods
Crashes on the following line

```
NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil)
```

The new cocoapods now uses swift modules and embedded frameworks, so DateTools.bundle is no longer at its old location, thus causing a crash due to nil being returned.

### PR DESCRIPTION
**Pull request by bassrock**
This fixes #56

### CODE REVIEW

**Comment by Fl0p** [comment]
and https://github.com/MatthewYork/DateTools/issues/67

**Comment by danthorpe** [comment]
Also fixes #69

**Comment by mergesort** [comment]
@MatthewYork Can these bundle fixes be merged in? I'm going to have to remove DateTools before my next app build if I can't get it to compile.

**Comment by mergesort** [comment]
The latest Cocoapods update (0.3.6.4) fixes the issues with bundles that were causing crashes.

**Comment by taylorfriesen** [comment]
Are there any plans to merge this soon? Still not working for me under Cocoapods 0.36.7, getting the same error as #56

**Comment by Dan2552** [comment]
+1, problems on `0.37.1`. This PR resolves the issue.

**Comment by MatthewYork** [comment]
Fixed in PR #84 and issued as cocoa pod version 1.6.0

**Pull request closed without merging**
