### PR TITLE
Fix deprecation warning after upgrading to Swift 3.1

### PR DESCRIPTION
**Pull request by albinekcom**

### CODE REVIEW

**Comment by UberJason** [comment]
@MatthewYork Hey there, any chance you can merge this in? Should be an ultra-low effort merge!

**Comment by nikolaeu** [comment]
@MatthewYork @UberJason +1

**Comment by musbaalbaki** [comment]
+1

**Comment by 3a4oT** [comment]
Hey! Can somebody merge it?

**Comment by parski** [comment]
Any day now.

**Comment by ludvigeriksson** [comment]
So, how about that merge?

**Comment by aerickson14** [comment]
+1

**Pull request merged**
